# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-10 18:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181110_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Name', max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='Description', null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('created_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='OrgHack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hackathon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Hackathon')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Name', max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='Description', null=True)),
                ('created_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='UserTeamHack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hackathon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Hackathon')),
            ],
        ),
        migrations.CreateModel(
            name='UserTeamProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Project')),
            ],
        ),
        migrations.RemoveField(
            model_name='userteam',
            name='birth',
        ),
        migrations.RemoveField(
            model_name='userteam',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='userteam',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userteam',
            name='name',
        ),
        migrations.AddField(
            model_name='userteamproject',
            name='userteam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.UserTeam'),
        ),
        migrations.AddField(
            model_name='userteamhack',
            name='userteam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.UserTeam'),
        ),
    ]
