# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-10 21:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_level_role_skill_userrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Name', max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='Description', null=True)),
                ('hackathon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Hackathon')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Name', max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='Description', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SectionHack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hackathon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Hackathon')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Section')),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Name', max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='Description', null=True)),
                ('birth', models.DateField(default=datetime.date.today)),
                ('hackathon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Hackathon')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.CharField(blank=True, default='Address', max_length=200, null=True),
        ),
    ]
