# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-11 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_userteam_max'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userteam',
            name='max',
        ),
        migrations.AddField(
            model_name='team',
            name='max',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
    ]
