# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-11 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20181111_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userteamhack',
            name='userteam',
        ),
        migrations.RemoveField(
            model_name='userteamproject',
            name='userteam',
        ),
        migrations.AddField(
            model_name='userteamhack',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Team'),
        ),
        migrations.AddField(
            model_name='userteamproject',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Team'),
        ),
    ]
