# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-11 03:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20181111_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='author',
        ),
    ]
