# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-11 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_team_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='img',
            field=models.CharField(default='../media/team.png', max_length=300),
        ),
    ]
